static_sites:
  - name: zhenzy-portfolio
    buildCommand: npm install && npm run build
    staticPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
